### PR TITLE
[WIFI-3232] Fix Docker Compose deployment

### PR DESCRIPTION
**Pull request by oblom0v**

### CODE REVIEW

**Review by leonidlm — APPROVED** [review]
Looks good!

**Comment by leonidlm** [comment]
@oblom0v shouldn't we also downgrade the rtty version or it was done in another PR already?

**Comment by dunaev-opsfleet** [comment]
@leonidlm I'd say it was downgraded already based on https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/pull/11/files#diff-d541cf839b4efa56b5927df28ba645c7dedcc082c7a2d8e442bfd9945684dea6R5 and the fact that MySQL is not in the services list

**Comment by oblom0v** [comment]
@leonidlm yep this was already done in https://github.com/Telecominfraproject/wlan-cloud-ucentral-deploy/pull/8.

**Pull request merged**
